name: Build and Deploy Vite Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or any LTS version compatible with your project (e.g., '18', '20', '22')
        cache: 'pnpm' # Cache pnpm dependencies for faster builds

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile # Use --frozen-lockfile for CI/CD environments

    - name: Build project
      run: pnpm run build # This command creates the deployable static assets (usually in 'dist/')

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist # Assuming Vite builds your project into a 'dist' folder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    permissions:
      pages: write # Required to deploy to GitHub Pages
      id-token: write # Required for OpenID Connect (OIDC) authentication

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Deploys the artifact uploaded in the 'build' job
        
